// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdlicluuurjmyyfjrben.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbGljbHV1dXJqbXl5ZmpyYmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjQyMTksImV4cCI6MjA2NzgwMDIxOX0.g1flpp-Soaf1X3Ggy5cDj4YePPKTdAlom3KX_k4QRKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});